root: true

parser: '@typescript-eslint/parser'

extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

rules:
  react/jsx-filename-extension: off
  react/prop-types: off
  '@typescript-eslint/no-non-null-assertion': off

